file_format: "1"
id: corne_choc_pro
name: Corne Choc Pro BT
type: board
arch: arm
features:
  - keys
  - underglow
  - studio
  - encoder
outputs:
  - usb
  - ble
url: https://keebart.com/products/corne-wireless
siblings:
  - corne_choc_pro_left
  - corne_choc_pro_right
